# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-09 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_diarycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarycomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.Diary'),
        ),
    ]
